services:
  celebcart:
    build:
      context: ./celebcart
      dockerfile: Dockerfile
    container_name: celebcart-web
    ports:
      - "3000:3000"
    env_file:
      - ./celebcart/.env
    depends_on:
      - socket-server
    restart: unless-stopped

  socket-server:
    build:
      context: ./socketServer
      dockerfile: Dockerfile
    container_name: celebcart-socket
    ports:
      - "4000:4000"
    env_file:
      - ./socketServer/.env
    restart: unless-stopped
